name: park_my_whip_residents
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  
  # Dependency Injection
  get_it: ^9.0.0
  
  # UI & Fonts
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.1.0
  
  # Local Storage
  shared_preferences: ^2.0.0
  flutter_secure_storage: ^10.0.0
  
  # Supabase Backend
  supabase_flutter: '>=1.10.0'
  
  # Utilities
  intl: 0.20.2
  pin_code_fields: ^8.0.0
  file_picker: '>=8.1.2'
  image_picker: '>=1.1.2'
  shimmer: ^3.0.0
  app_links: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
   - family: appIcons
     fonts:
      - asset: assets/fonts/app_icons_font.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true

flutter_native_splash:
  image: assets/images/logo.png
  color: "#FFFFFF"
  android_12:
    image: assets/images/android12_logo.png
    color: "#FFFFFF"
  android: true
  ios: true
  web: false
  fullscreen: true
